# Generated by Django 4.1.5 on 2023-02-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(default='null', max_length=100)),
                ('notice_desc', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('floor_no', models.IntegerField()),
                ('flat_no', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
