# Generated by Django 4.1.5 on 2023-03-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_associationprofile_user_and_more'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.association'),
        ),
    ]
