# Generated by Django 4.1.5 on 2023-03-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_notice_notice_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
