# Generated by Django 4.1.5 on 2023-02-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_notices_notice_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notices',
            new_name='Notice',
        ),
    ]
