# Generated by Django 4.1.5 on 2023-02-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_remove_complaint_issued_date2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
