# Generated by Django 4.1.5 on 2023-03-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='UTR',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
