# Generated by Django 4.1.5 on 2023-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_alter_complaint_resolved_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('item', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
