# Generated by Django 4.1.5 on 2023-03-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_associationprofile_user_and_more'),
        ('association', '0003_alter_payment_utr'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.owner'),
        ),
    ]
