# Generated by Django 4.1.5 on 2023-03-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reciept_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
