# Generated by Django 4.1.5 on 2023-03-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_for',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
