# Generated by Django 4.1.5 on 2023-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_payment_payment_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_for',
            field=models.CharField(choices=[('MB', 'Maintenance Bill'), ('FH', 'Function Hall'), ('OB', 'Other Bill')], max_length=2, null=True),
        ),
    ]
