# Generated by Django 4.1.5 on 2023-03-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0010_alter_payment_payment_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline')], max_length=2, null=True),
        ),
    ]
