# Generated by Django 4.1.5 on 2023-03-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='FlatNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='FloorNo',
            field=models.IntegerField(null=True),
        ),
    ]
