# Generated by Django 4.1.5 on 2023-03-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_associationprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationprofile',
            name='AssociationAddress',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='OwnerAddress',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='OwnerpNo',
        ),
        migrations.AddField(
            model_name='associationprofile',
            name='AssociationPhNo',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='associationprofile',
            name='ProfilePic',
            field=models.ImageField(null=True, upload_to='owner/dps'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='OwnerPhNo',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='ProfilePic',
            field=models.ImageField(null=True, upload_to='owner/dps'),
        ),
        migrations.AlterField(
            model_name='associationprofile',
            name='AssociationRole',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='FloorNo',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
